package ai.mayra.app.learning

import java.security.SecureRandom

/**
 * UI-neutral controller for owner-reviewed memory actions.
 *
 * Surfaces never mutate DAO entities directly. Destructive reset requires a short-lived,
 * single-use confirmation token generated by this controller.
 */
class MayraLearningReviewController(
    private val gateway: LearningReviewGateway,
    private val now: () -> Long = System::currentTimeMillis,
    private val tokenSource: () -> String = ::secureToken
) {
    private var pendingReset: PendingReset? = null

    suspend fun refresh(maxPerSection: Int = 20): LearningReviewControllerState = runCatching {
        val bounded = maxPerSection.coerceIn(1, 20)
        val snapshot = MayraLearningReviewModel.snapshot(
            pending = gateway.pending(),
            approved = gateway.approved(bounded),
            maxPerSection = bounded
        )
        LearningReviewControllerState.Ready(snapshot)
    }.getOrElse { LearningReviewControllerState.Error(safeMessage(it)) }

    suspend fun approve(key: String): LearningReviewActionResult = mutate(key, "approve") {
        gateway.approve(it)
    }

    suspend fun reject(key: String): LearningReviewActionResult = mutate(key, "reject") {
        gateway.reject(it)
    }

    suspend fun forget(key: String): LearningReviewActionResult = mutate(key, "forget") {
        gateway.forget(it)
    }

    fun requestForgetAll(): ForgetAllChallenge {
        val challenge = ForgetAllChallenge(
            token = tokenSource().take(64),
            expiresAtEpochMs = now() + RESET_TOKEN_TTL_MS
        )
        pendingReset = PendingReset(challenge.token, challenge.expiresAtEpochMs, used = false)
        return challenge
    }

    suspend fun confirmForgetAll(token: String): LearningReviewActionResult {
        val current = pendingReset
            ?: return LearningReviewActionResult.Denied("No forget-all confirmation is pending")
        if (current.used) return LearningReviewActionResult.Denied("Confirmation was already used")
        if (now() > current.expiresAtEpochMs) {
            pendingReset = null
            return LearningReviewActionResult.Denied("Confirmation expired")
        }
        if (!constantTimeEquals(current.token, token)) {
            return LearningReviewActionResult.Denied("Confirmation token does not match")
        }

        pendingReset = current.copy(used = true)
        return runCatching {
            val count = gateway.forgetAll()
            pendingReset = null
            LearningReviewActionResult.Success("Forgot $count memories", affected = count)
        }.getOrElse {
            pendingReset = null
            LearningReviewActionResult.Failed(safeMessage(it))
        }
    }

    fun cancelForgetAll() {
        pendingReset = null
    }

    private suspend fun mutate(
        rawKey: String,
        action: String,
        block: suspend (String) -> Boolean
    ): LearningReviewActionResult {
        val key = rawKey.trim().take(80)
        if (key.isBlank()) return LearningReviewActionResult.Denied("Memory key is empty")
        return runCatching {
            if (block(key)) {
                LearningReviewActionResult.Success("Memory ${action}d", affected = 1)
            } else {
                LearningReviewActionResult.NotFound(key)
            }
        }.getOrElse { LearningReviewActionResult.Failed(safeMessage(it)) }
    }

    private data class PendingReset(val token: String, val expiresAtEpochMs: Long, val used: Boolean)

    companion object {
        private const val RESET_TOKEN_TTL_MS = 60_000L

        private fun secureToken(): String {
            val bytes = ByteArray(18)
            SecureRandom().nextBytes(bytes)
            return bytes.joinToString("") { "%02x".format(it) }
        }

        private fun safeMessage(error: Throwable): String =
            error.message?.replace(Regex("\\s+"), " ")?.trim()?.take(160)
                ?.takeIf(String::isNotBlank) ?: "Memory operation failed"

        private fun constantTimeEquals(expected: String, actual: String): Boolean {
            val left = expected.toByteArray(Charsets.UTF_8)
            val right = actual.toByteArray(Charsets.UTF_8)
            var diff = left.size xor right.size
            val max = maxOf(left.size, right.size)
            for (index in 0 until max) {
                val a = if (index < left.size) left[index].toInt() else 0
                val b = if (index < right.size) right[index].toInt() else 0
                diff = diff or (a xor b)
            }
            return diff == 0
        }
    }
}

interface LearningReviewGateway {
    suspend fun pending(): List<LearnedMemoryEntity>
    suspend fun approved(limit: Int): List<LearnedMemoryEntity>
    suspend fun approve(key: String): Boolean
    suspend fun reject(key: String): Boolean
    suspend fun forget(key: String): Boolean
    suspend fun forgetAll(): Int
}

class RepositoryLearningReviewGateway(
    private val repository: MayraLearningRepository
) : LearningReviewGateway {
    override suspend fun pending(): List<LearnedMemoryEntity> = repository.pending()
    override suspend fun approved(limit: Int): List<LearnedMemoryEntity> = repository.approvedContext(limit)
    override suspend fun approve(key: String): Boolean = repository.approve(key)
    override suspend fun reject(key: String): Boolean = repository.reject(key)
    override suspend fun forget(key: String): Boolean = repository.forget(key)
    override suspend fun forgetAll(): Int = repository.forgetAll()
}

sealed interface LearningReviewControllerState {
    data class Ready(val snapshot: LearningReviewSnapshot) : LearningReviewControllerState
    data class Error(val message: String) : LearningReviewControllerState
}

sealed interface LearningReviewActionResult {
    data class Success(val message: String, val affected: Int) : LearningReviewActionResult
    data class NotFound(val key: String) : LearningReviewActionResult
    data class Denied(val reason: String) : LearningReviewActionResult
    data class Failed(val message: String) : LearningReviewActionResult
}

data class ForgetAllChallenge(val token: String, val expiresAtEpochMs: Long)
